\c payment_db;

ALTER TABLE refunds ADD COLUMN IF NOT EXISTS recipient_type VARCHAR(30) DEFAULT 'CUSTOMER';
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS shipper_name VARCHAR(100);
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS shipper_phone VARCHAR(30);
