<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.beverage</groupId>
    <artifactId>springboot-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>shared-jwt</module>
        <module>shared-storage</module>
        <module>auth-service</module>
        <module>product-service</module>
        <module>payment-service</module>
        <module>order-service</module>
        <module>inventory-service</module>
        <module>dashboard-service</module>
    </modules>
</project>
